sonar.projectKey=shop
sonar.projectName=Shop
sonar.organization=com.example
sonar.host.url=http://localhost:9000
sonar.token=sqa_8823043b247474012611e320469281d02095740a
sonar.sourceEncoding=UTF-8
sonar.login=admin
sonar.password=admin1

# export PATH="/home/wjh/All/rzeczy/own_progs/other/sonar-scanner-8.0.1.6346-linux-x64/bin:$PATH"
