name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Lint-JS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
        working-directory: ./5_react/frontend
      - name: Run ESLint
        run: npm run lint
        working-directory: ./5_react/frontend
